src/components/Editor/Editor.tsx
src/components/Editor/constants.ts
src/components/Editor/plugins.ts
src/components/HoveredMenu/HoveredMenu.tsx

Empty node while text splitting
Issue: https://github.com/Darginec05/Editor-Yopta/issues

issue1 fix adding an empty node while text splitting

---

.eslintrc.json
.github/workflows/playwright.yml
.gitignore
.prettierignore
e2e/example.spec.ts
examples/pages/styling/index.tsx
package.json
playwright.config.ts
src/YoptaEditor.test.tsx
src/components/Editor/SuggestionElementList/SuggestionElementList.tsx
tests-examples/demo-todo-app.spec.ts
tests/setup.js
vitest.config.ts
yarn.lock

Add e2e tests and unit tests configuration

Setup tests

---

packages/yoopta-editor/package.json
packages/yoopta-editor/src/components/Editor/Editor.tsx

75 autofocus is triggered even if the value is false

---

packages/yoopta-editor/package.json
packages/yoopta-editor/src/contexts/YooptaContext/YooptaContext.tsx
web/package.json
web/yarn.lock

Fix active selected item in default toolbar

82 selecting list item shows wrong element type

---

package.json
packages/actionMenu/package.json
packages/exports/package.json
packages/linkTool/package.json
packages/marks/package.json
packages/toolbar/package.json
packages/yoopta-blockquote/package.json
packages/yoopta-callout/package.json
packages/yoopta-chatGPT-assistant/package.json
packages/yoopta-code/package.json
packages/yoopta-editor/package.json
packages/yoopta-embed/package.json
packages/yoopta-file/package.json
packages/yoopta-headings/package.json
packages/yoopta-image/package.json
packages/yoopta-link/package.json
packages/yoopta-lists/package.json
packages/yoopta-paragraph/package.json
packages/yoopta-renderer/package.json
packages/yoopta-video/package.json

https://github.com/Darginec05/Yoopta-Editor/issues/104

Fix missing dist files in build versions

---

README.md

- displays latest rating
- clickable to make it easier for people to add their rating

repo rater clickable badge with rating

---

packages/core/src/UI/BlockOptions/BlockOptions.tsx
packages/core/src/UI/BlockOptions/utils.ts
packages/core/src/components/Block/BlockActions.tsx
packages/core/src/components/Block/hooks.ts
packages/core/src/components/Editor/Editor.tsx
packages/development/src/pages/dev/index.tsx

Issues: 
- https://github.com/Darginec05/Yoopta-Editor/issues/129
- https://github.com/Darginec05/Yoopta-Editor/issues/77

Open ActionMenu on plus block action click

---

README.md

Thanks for awesome project!
I fixed readme text.
This PR about:
* README fix
* Fixed missing description for passing an editor instance to YooptaEditor

[README] pass editor instance to YooptaEditor

---

package.json
packages/core/src/components/Block/BlockActions.tsx
packages/marks/src/components/code.tsx
web/next-example/src/components/examples/withBaseFullSetup/initValue.ts

Fix error when adding plus button on plugins with custom editor

Fix error when adding plus button on plugins with custom editor

---

packages/core/src/handlers/onKeyDown.ts
packages/development/src/pages/dev/index.tsx

Fix error when prev block with custom editor on backspace

Fix error when prev block with custom editor on backspace

---

packages/core/src/editor/core/setEditorValue.ts
packages/core/src/editor/index.tsx
packages/core/src/editor/types.ts
packages/core/src/index.ts
packages/development/src/pages/dev/index.tsx

Added new method to editor: 
- setEditorValue - method to set new value to the editor

Added setEditorValue to API

---

package.json
packages/development/src/pages/dev/index.tsx
packages/image/src/types.ts
packages/image/src/ui/FileUploader.tsx
packages/image/src/ui/Image.tsx
packages/video/src/types.ts
packages/video/src/ui/FileUploader.tsx

Added fit to onUpload method for image and video

Added fit to onUpload method for media

---

README.md
packages/plugins/lists/README.md

Docs for @yoopta/lists

---

README.md

Setup FUNDING.yml and sponsor button

Add badges and sponsor button

---

packages/core/editor/src/editor/blocks/getBlock.ts
packages/core/editor/src/editor/blocks/index.ts
packages/core/editor/src/editor/elements/getElementEntry.ts
packages/core/editor/src/editor/elements/index.tsx
packages/core/editor/src/editor/elements/insertElementText.ts
packages/core/editor/src/editor/index.tsx
packages/core/editor/src/editor/types.ts
packages/development/src/pages/dev/index.tsx

Added new API methods: getBlock for Blocks and insertElementText for Elements
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
https://github.com/Darginec05/Yoopta-Editor/issues/193

New API methods: getBlock and insertElementText 

---

packages/development/src/utils/yoopta/plugins.tsx
packages/plugins/code/src/plugin/index.tsx

Added escape html function to serialize for Code plugin

Added escape html function to serialize for Code plugin

---

package.json
packages/core/editor/src/parsers/deserializeHTML.ts
packages/core/exports/src/html/deserialize.ts
packages/plugins/table/src/components/TableColumnOptions.tsx

https://github.com/Darginec05/Yoopta-Editor/issues/201

201 bug markdown serializer strips out asterisks

---

packages/plugins/embed/src/plugin/index.tsx
packages/plugins/embed/src/providers/Instagram.tsx
packages/plugins/embed/src/providers/Twitter.tsx
packages/plugins/embed/src/types.ts
packages/plugins/embed/src/ui/Embed.tsx
packages/plugins/embed/src/ui/EmbedComponent.tsx
packages/plugins/embed/src/ui/EmbedLinkUploader.tsx
packages/plugins/embed/src/utils/providers.ts
packages/tools/toolbar/src/components/DefaultToolbarRender.tsx
packages/tools/toolbar/src/styles.css

Added insta provider && fixed twitter provider
https://github.com/Darginec05/Yoopta-Editor/issues/283

added inst provider to embed && fixed twitter

---

packages/core/editor/src/index.ts
packages/core/editor/src/parsers/deserializeTextNodes.ts
packages/core/editor/src/parsers/serializeTextNodes.ts
packages/core/exports/src/html/deserialize.ts
packages/plugins/callout/src/plugin/index.tsx
packages/plugins/link/src/plugin/index.tsx
packages/plugins/lists/src/elements/NumberedList.tsx
packages/plugins/lists/src/plugin/BulletedList.tsx
packages/plugins/lists/src/plugin/NumberedList.tsx
packages/plugins/lists/src/plugin/TodoList.tsx
packages/plugins/paragraph/src/plugin/index.tsx
packages/plugins/table/src/parsers/html/deserialize.ts
packages/plugins/table/src/parsers/html/serialize.ts
packages/plugins/table/src/plugin/Table.tsx

Fixesd text nodes deserialize/serialize
https://github.com/Darginec05/Yoopta-Editor/issues/264

Text nodes deserialize/serialize

---

packages/plugins/code/package.json
packages/plugins/code/src/ui/Code.tsx
packages/plugins/code/src/utils/languages.tsx
yarn.lock

Added `bash/shell` to code plugin
https://github.com/Darginec05/Yoopta-Editor/issues/286

286 feature bash option for codeblock

---

packages/core/editor/src/components/Block/BlockActions.tsx
packages/core/editor/src/components/Editor/Editor.tsx
packages/core/editor/src/components/Editor/selection.ts

https://github.com/Darginec05/Yoopta-Editor/issues/307

Fix bug with dnd

---

packages/core/editor/package.json
packages/core/editor/src/plugins/extenstions/withInlines.ts
yarn.lock

https://github.com/Darginec05/Yoopta-Editor/issues/319

Fix isUrl check

---

packages/plugins/lists/src/plugin/BulletedList.tsx
packages/tools/toolbar/package.json
packages/tools/toolbar/src/components/HighlightColor.tsx
yarn.lock

Added `react-colorful`  to Highlight mark
- https://github.com/yoopta-editor/Yoopta-Editor/issues/419

Added color picker to highlight mark

---

README.md
packages/core/editor/README.md
packages/core/editor/src/YooptaEditor.tsx
packages/development/src/pages/dev/index.tsx

Add `onPathChange` prop
https://github.com/yoopta-editor/Yoopta-Editor/issues/422

Add onPathChange prop

---

packages/core/editor/src/editor/blocks/deleteBlock.ts

Added onDestroy to deleteBlock
https://github.com/yoopta-editor/Yoopta-Editor/issues/427

Added `onDestroy` event to `deleteBlock`

---

packages/core/editor/src/YooptaEditor.tsx
packages/core/editor/src/editor/types.ts
packages/core/editor/src/index.ts
packages/core/editor/src/plugins/SlateEditorComponent.tsx
packages/core/i18n/README.md
packages/core/i18n/src/context/YooptaI18nProvider.tsx
packages/core/i18n/src/extension/withTranslations.ts
packages/core/i18n/src/hooks/useTranslation.ts
packages/core/i18n/src/index.ts
packages/core/i18n/src/types/i18n-yoo-editor.ts
packages/core/i18n/src/types/index.ts
packages/core/i18n/src/types/translation-options.ts
packages/development/src/components/FixedToolbar/FixedToolbar.tsx
packages/development/src/pages/dev/index.tsx

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

feat: emit language-change event on setLanguage

---

packages/tools/toolbar/src/components/Toolbar.tsx

Fixed bug with loss of focus in the toolbar for safari browsers
- https://github.com/yoopta-editor/Yoopta-Editor/issues/451

Fix losing focus bug for toolbar in Safari browsers

---

packages/tools/toolbar/src/components/HighlightColor.tsx

Added type button to prevent form submit
- https://github.com/yoopta-editor/Yoopta-Editor/issues/453

Added type button to prevent form submit

---

packages/tools/toolbar/src/components/HighlightColor.tsx

Decreased delay when selecting highlight color in ColorPicker
- https://github.com/yoopta-editor/Yoopta-Editor/issues/446

Decrease delay when selecting highlight color in ColorPicker

---

packages/plugins/image/src/styles.css
packages/plugins/image/src/ui/ImageComponent.tsx

Added zoom-in for images
- https://github.com/yoopta-editor/Yoopta-Editor/issues/479

Added zoom-in for images

---

packages/core/editor/src/components/Editor/Editor.tsx
packages/core/editor/src/components/Editor/selection.ts
packages/core/editor/src/components/SelectionBox/hooks.ts
packages/core/editor/src/editor/blocks/toggleBlock.ts
packages/core/editor/src/editor/core/applyTransforms.ts
packages/core/editor/src/editor/core/history.ts
packages/core/editor/src/editor/textFormats/toggle.tsx
packages/core/editor/src/editor/textFormats/update.tsx
packages/core/editor/src/editor/types.ts
packages/core/editor/src/handlers/onKeyDown.ts
packages/core/editor/src/plugins/SlateEditorComponent.tsx
packages/core/editor/src/styles.css
packages/development/src/pages/dev/index.tsx
packages/tools/toolbar/src/components/DefaultToolbarRender.tsx
packages/tools/toolbar/src/components/HighlightColor.tsx
packages/tools/toolbar/src/components/Toolbar.tsx
packages/tools/toolbar/src/components/utils.ts

Toolbar should be open when several blocks  selected
https://github.com/yoopta-editor/Yoopta-Editor/issues/481

Toolbar for several selected blocks

---

packages/core/editor/src/UI/BlockOptions/utils.ts
packages/tools/action-menu/src/components/ActionMenuList.tsx
packages/tools/action-menu/src/components/utils.ts

Fix bug when change block to another type and block text disappears
https://github.com/yoopta-editor/Yoopta-Editor/issues/484

Fix bug when change block to another type and block text disappears

---

packages/plugins/lists/src/elements/NumberedList.tsx

Fixed bug with numeric-list-continuation
https://github.com/yoopta-editor/Yoopta-Editor/issues/431

Fix bug with numeric-list-continuation
