yoopta-editor/Yoopta-Editor

src/components/Editor/SuggestionElementList/SuggestionElementList.tsx, src/components/Editor/Toolbar/Toolbar.tsx, src/components/ImageEditor/index.tsx, src/components/NodeSettings/NodeSettings.tsx, src/components/VideoEditor/VideoEditor.tsx, src/utils.ts
Fixed onCopy function for YoptaRenderer and YoptaEditor.
Copy only selected fields of content
=> 19-oncopy-function-overwrites-selected-fields fix copy content

README.md
=> Adding get started instruction

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
- added contributing guide and code of conduct
Related to the issue https://github.com/Darginec05/Yoopta-Editor/issues/117
=> [FEAT] Contributing guide

CONTRIBUTING.md, README.md, packages/plugins/paragraph/README.md
=> Docs for paragraph

packages/plugins/embed/src/ui/Placeholder.tsx, packages/plugins/file/src/ui/Placeholder.tsx, packages/plugins/image/src/ui/Placeholder.tsx, packages/plugins/video/src/ui/Placeholder.tsx, packages/tools/action-menu/src/components/DefaultActionMenuRender.tsx, packages/tools/link-tool/src/components/DefaultLinkToolRender.tsx
I discovered an issue while using the image plugin in the editor. The plugin renders a placeholder button, which I need to click to open a popover. However, clicking this button inadvertently triggers form submissions because it lacks the type="button" attribute. 
=> fix add type attribute to prevent form submission

packages/tools/link-tool/src/components/DefaultLinkToolRender.tsx, packages/tools/link-tool/src/types.ts, packages/tools/toolbar/src/components/DefaultToolbarRender.tsx
This pull request introduces the ability to dynamically update the `target` and `rel` attributes of a link within the `LinkTool`. This enhancement addresses a use case where these attributes need to be customizable for different links, allowing flexibility and control over link behavior. The current implementation allows passing attributes like target and rel through the onSave callback, providing the ability to customize each link based on specific needs.
Fixes #159 
Please delete options that are not relevant.
=> feat add dynamic handling for link rel and target attributes

packages/plugins/embed/src/utils/providers.ts
Twitter / X changed its domain from twitter.com to x.com recently, so when users click the "Copy link" button, they will get a "x.com" link, which the embed plugin can't handle.
This PR checks for x.com links and treat them as twitter. 
https://github.com/Darginec05/Yoopta-Editor/issues/165
=> fix: make it possible to embed x.com post with the embed plugin

packages/core/editor/src/components/Editor/dnd.ts
I changed the way the drag button behaves with the drag behavior of @dnd-kit.
Now, clicking the drag button will open the action menu without altering the drag functionality.
Fixes #171
=> fix: action menu don't open on click

packages/core/exports/src/markdown/deserialize.ts, packages/core/exports/src/text/serialize.ts, packages/development/src/pages/dev/index.tsx, packages/plugins/lists/src/elements/NumberedList.tsx
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
https://github.com/Darginec05/Yoopta-Editor/issues/192
=> Fix number list ordering

packages/tools/action-menu/src/components/ActionMenuList.tsx
Fixes issue #327 
The bug was caused by the `inline()` reference. Removing it fixed the action menu. I've attached videos showing the issue before and after the fix.
https://github.com/user-attachments/assets/beb24ca2-2fee-4f66-852f-0b93fe0f6887
https://github.com/user-attachments/assets/24a41060-f113-4ecf-b030-eda6df3268a7
=> Fix: Positioning bug of Action Menu

package.json, yarn.lock
This PR removes the deprecated node-sass dependency, as it is no longer in use.
=> Remove node-sass package

packages/core/editor/src/extensions/shortcuts.tsx
- #333 
- #206 
When using markdown symbols (e.g., #, - ) to convert an existing text block into a heading or bullet list, the entire text block gets removed, leaving a blank block with the new markdown format.
Attaching a video of the fix
https://github.com/user-attachments/assets/eef5b112-e37d-4691-a8ef-2daa2f763283
=> [Fix] Markdown shortcut removes existing block

packages/core/exports/package.json, packages/core/starter-kit/package.json, packages/core/yoopta-chatGPT-assistant/package.json, packages/core/yoopta-renderer/package.json, packages/marks/package.json, packages/plugins/accordion/package.json, packages/plugins/blockquote/package.json, packages/plugins/callout/package.json, packages/plugins/code/package.json, packages/plugins/divider/package.json, packages/plugins/embed/package.json, packages/plugins/file/package.json, packages/plugins/headings/package.json, packages/plugins/image/package.json, packages/plugins/link/package.json, packages/plugins/lists/package.json, packages/plugins/mention/package.json, packages/plugins/paragraph/package.json, packages/plugins/table/package.json, packages/plugins/video/package.json, packages/tools/action-menu/package.json, packages/tools/link-tool/package.json, packages/tools/toolbar/package.json
Many of the packages contain broken links to their GitHub repositories, leading to a 404 error when accessed via npm or yarn.
https://github.com/user-attachments/assets/43459e70-5b91-485a-a4f6-d1d56c00eb0d
=> Broken repo link in packages

packages/core/editor/src/contexts/YooptaContext/YooptaContext.tsx, packages/core/editor/src/editor/index.tsx, packages/core/editor/src/editor/types.ts, packages/core/editor/src/parsers/getEmail.ts, packages/core/editor/src/plugins/types.ts, packages/development/src/components/FixedToolbar/FixedToolbar.tsx, packages/plugins/blockquote/src/plugin/index.tsx, packages/plugins/callout/src/plugin/index.tsx, packages/plugins/code/src/plugin/index.tsx, packages/plugins/divider/src/plugin/index.tsx, packages/plugins/file/src/plugin/index.tsx, packages/plugins/headings/src/plugin/HeadingOne.tsx, packages/plugins/headings/src/plugin/HeadingThree.tsx, packages/plugins/headings/src/plugin/HeadingTwo.tsx, packages/plugins/image/src/plugin/index.tsx, packages/plugins/link/src/plugin/index.tsx, packages/plugins/lists/src/plugin/BulletedList.tsx, packages/plugins/lists/src/plugin/NumberedList.tsx, packages/plugins/lists/src/plugin/TodoList.tsx, packages/plugins/paragraph/src/plugin/index.tsx
Allow to get email html from current editor instance and  content.
=> Add email export, implement export for paragraph and headings

packages/plugins/embed/src/providers/Loom.tsx, packages/plugins/embed/src/providers/Wistia.tsx, packages/plugins/embed/src/types.ts, packages/plugins/embed/src/ui/EmbedComponent.tsx, packages/plugins/embed/src/utils/providers.ts, packages/plugins/video/src/plugin/index.tsx, packages/plugins/video/src/types.ts, packages/plugins/video/src/ui/EmbedUploader.tsx, packages/plugins/video/src/ui/LoomPlayer.tsx, packages/plugins/video/src/ui/VideoComponent.tsx, packages/plugins/video/src/ui/WistiaPlayer.tsx, packages/plugins/video/src/utils/providers.ts
Added the ability to add Loom & Wistia videos in the Video plugin. Note that I'm not used to Typescrpt at all, so I might need some help with this if you see issues.
I also fixed a typo and added more video types to this element:
"Upload from device, embed from Youtube, Vimeo, DailyMotion, Loom, Wistia"
=> Add loom and wistia videos

packages/core/exports/src/markdown/deserialize.ts
If we try to `deserialize` the image with it's markdown syntax like as given below
```js
const content = markdown.deserialize(editor, "![Sonny and Mariel high fiving.](https://content.codecademy.com/courses/learn-cpp/community-challenge/highfive.gif)");
editor.setEditorValue(content);
console.log(content);
```
It could not able to convert it into it's respective image component/render.
Issue is with the marked, cause this library parse this image syntax and convert it to sometime like this
```markdown
```
above markdown converts to this image tag with wrapped inside p tag.
```html
<p><img src="url" atl="Alt text"/></p>
```
that's why yoopta-editor can't able to parse the image tag markdown and render it to ImageRender component. 
=> fix: image markdown couldn't able to deserialize due it's not implemented

packages/core/editor/src/plugins/hooks.ts
Currently, when there are two or more inline elements, only the last element will be treat as inline, and others will be treat as blocks. In the other words, only one inline plugin can exist. For example, when I use both mention(inlineVoid) and link(inline) element, the mention element cannot be inserted in a paragraph, cause it will be treat as a block element.
=> fix issue: when there are two or more inline elements

packages/plugins/file/src/types.ts, packages/plugins/file/src/ui/FileUploader.tsx, packages/plugins/image/src/types.ts, packages/plugins/image/src/ui/FileUploader.tsx, packages/plugins/video/src/types.ts, packages/plugins/video/src/ui/FileUploader.tsx
Currently on upload any error is silent and a user does not know what happened.
Fixes # [issue](https://github.com/yoopta-editor/Yoopta-Editor/issues/464)
=> extend [Image|Video|File]PluginOptions  with onError

packages/core/editor/src/styles.css
When clicking on the placeholder ("Type '/' for commands") the Block didn't gain focus. This is because the placeholder is a pseudo-element that was blocking the click event.
This change fixes it.
https://github.com/user-attachments/assets/cf04d854-13be-4eee-9d47-f70e08611168
https://github.com/user-attachments/assets/d9de7606-771e-4623-b90a-f589ad7d320a
=> fix: click on placeholder adds focus to block

packages/core/editor/src/editor/index.tsx
https://github.com/yoopta-editor/Yoopta-Editor/issues/466
> 
When there are multiple instances of the YooptaEditor the onChange event is triggered for all instances with the same value AND
Also if you perform undo redo actions with ctrl+z and ctrl+y they are applied for all editor instances not only for the focused one (WIP)
I have made it such that the editors have their own local events instead of global and now callbacks are local per editor instantiation.
- [ X I have performed a self-review of my own code
=> fix(editor): Fixed events for multiple editors by making them not global
